# Generated by Django 3.1.2 on 2021-02-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(help_text='usuario associado:', max_length=20)),
                ('nomeLink', models.CharField(help_text='Nome do Link:', max_length=20)),
                ('chaveLink', models.CharField(default='', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateField(auto_now_add=True)),
                ('dado', models.IntegerField(help_text='dado')),
                ('linkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.links')),
            ],
            options={
                'ordering': ['-timeStamp'],
            },
        ),
    ]
