# Generated by Django 3.1.5 on 2021-01-27 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='dispositivo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=30)),
                ('link_api', models.TextField()),
                ('dono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.usuario')),
            ],
        ),
    ]
